/-
Erdős Problem 202 — Park–Pham layer, Stage 1.

Finite Boolean families, upper closures, increasing predicate, minimal
members, and the `ell(U)` complexity bound used by the Park–Pham
expectation-threshold theorem.

All definitions live over a finite ground universe `X : Finset α`. We
avoid any general measure theory; subsets of `X` are represented as
`Finset α` filtered by `S ⊆ X`.
-/

import Mathlib
import Erdos.P202.SpreadDefs

namespace Erdos202
namespace ParkPham

open Finset
open scoped BigOperators

variable {α : Type*}

section

variable [DecidableEq α]

/-- The upper closure of `A` inside the universe `X`: the set of subsets
`T ⊆ X` that contain some member of `A`. -/
def upClosureIn (X : Finset α) (A : Finset (Finset α)) : Finset (Finset α) :=
  X.powerset.filter fun T => ∃ S ∈ A, S ⊆ T

@[simp]
lemma mem_upClosureIn {X : Finset α} {A : Finset (Finset α)} {T : Finset α} :
    T ∈ upClosureIn X A ↔ T ⊆ X ∧ ∃ S ∈ A, S ⊆ T := by
  simp [upClosureIn, mem_powerset]

/-- A family contained in the ground universe is contained in its upper
closure. -/
lemma subset_upClosureIn {X : Finset α} {A : Finset (Finset α)}
    (hAX : ∀ S ∈ A, S ⊆ X) :
    A ⊆ upClosureIn X A := by
  intro S hS
  exact mem_upClosureIn.mpr ⟨hAX S hS, S, hS, subset_refl _⟩

/-- Upper closure is monotone in the generating family. -/
lemma upClosureIn_mono {X : Finset α} {A B : Finset (Finset α)}
    (hAB : A ⊆ B) :
    upClosureIn X A ⊆ upClosureIn X B := by
  intro T hT
  rcases mem_upClosureIn.mp hT with ⟨hTX, S, hSA, hST⟩
  exact mem_upClosureIn.mpr ⟨hTX, S, hAB hSA, hST⟩

/-- A nonempty upper closure has a nonempty generating family. -/
lemma nonempty_of_upClosureIn_nonempty {X : Finset α} {A : Finset (Finset α)}
    (h : (upClosureIn X A).Nonempty) :
    A.Nonempty := by
  rcases h with ⟨T, hT⟩
  rcases mem_upClosureIn.mp hT with ⟨_, S, hSA, _⟩
  exact ⟨S, hSA⟩

/-- The empty set is in an upper closure exactly when it is one of the
generators. -/
lemma empty_mem_upClosureIn_iff {X : Finset α} {A : Finset (Finset α)} :
    (∅ : Finset α) ∈ upClosureIn X A ↔ (∅ : Finset α) ∈ A := by
  constructor
  · intro h
    rcases mem_upClosureIn.mp h with ⟨_, S, hSA, hSempty⟩
    have hS_eq : S = ∅ := by
      apply Finset.eq_empty_iff_forall_notMem.mpr
      intro x hx
      simpa using hSempty hx
    simpa [hS_eq] using hSA
  · intro h
    exact mem_upClosureIn.mpr ⟨Finset.empty_subset X, ∅, h, subset_refl _⟩

lemma empty_not_mem_upClosureIn_iff {X : Finset α} {A : Finset (Finset α)} :
    (∅ : Finset α) ∉ upClosureIn X A ↔ (∅ : Finset α) ∉ A := by
  rw [empty_mem_upClosureIn_iff]

/-- A family `U ⊆ X.powerset` is increasing if it is closed under taking
supersets inside `X`. -/
def IncreasingIn (X : Finset α) (U : Finset (Finset α)) : Prop :=
  ∀ S ∈ U, ∀ T : Finset α, T ⊆ X → S ⊆ T → T ∈ U

/-- The upper closure of any family is increasing. -/
lemma increasingIn_upClosureIn (X : Finset α) (A : Finset (Finset α)) :
    IncreasingIn X (upClosureIn X A) := by
  intro S hS T hTX hST
  rcases mem_upClosureIn.mp hS with ⟨_, S₀, hS₀A, hS₀S⟩
  exact mem_upClosureIn.mpr ⟨hTX, S₀, hS₀A, hS₀S.trans hST⟩

/-- An increasing family inside `X` is equal to its upper closure. -/
lemma upClosureIn_eq_self_of_increasing {X : Finset α} {U : Finset (Finset α)}
    (hUX : ∀ S ∈ U, S ⊆ X) (hIncr : IncreasingIn X U) :
    upClosureIn X U = U := by
  ext T
  constructor
  · intro hT
    rcases mem_upClosureIn.mp hT with ⟨hTX, S, hSU, hST⟩
    exact hIncr S hSU T hTX hST
  · intro hTU
    exact mem_upClosureIn.mpr ⟨hUX T hTU, T, hTU, subset_refl _⟩

/-- In an increasing family, the upper closure generated by any member is
contained in the family. -/
lemma upClosureIn_singleton_subset_of_mem_increasing
    {X : Finset α} {U : Finset (Finset α)} {S : Finset α}
    (hIncr : IncreasingIn X U) (hS : S ∈ U) :
    upClosureIn X {S} ⊆ U := by
  intro T hT
  rcases mem_upClosureIn.mp hT with ⟨hTX, R, hR, hRT⟩
  have hR_eq : R = S := by simpa using hR
  exact hIncr S hS T hTX (by simpa [hR_eq] using hRT)

/-- Taking upper closure twice does not change the family. -/
lemma upClosureIn_idempotent (X : Finset α) (A : Finset (Finset α)) :
    upClosureIn X (upClosureIn X A) = upClosureIn X A := by
  exact upClosureIn_eq_self_of_increasing
    (fun S hS => (mem_upClosureIn.mp hS).1)
    (increasingIn_upClosureIn X A)

omit [DecidableEq α] in
/-- A nonempty increasing family on `X` contains the top element `X`. -/
lemma top_mem_of_nonempty_increasing {X : Finset α} {U : Finset (Finset α)}
    (hUX : ∀ S ∈ U, S ⊆ X) (hIncr : IncreasingIn X U)
    (hU : U.Nonempty) :
    X ∈ U := by
  rcases hU with ⟨S, hS⟩
  exact hIncr S hS X (subset_refl X) (hUX S hS)

omit [DecidableEq α] in
/-- An increasing family on `X` that contains `∅` is the whole Boolean cube. -/
lemma eq_powerset_of_empty_mem_increasing {X : Finset α} {U : Finset (Finset α)}
    (hUX : ∀ S ∈ U, S ⊆ X) (hIncr : IncreasingIn X U)
    (hEmpty : (∅ : Finset α) ∈ U) :
    U = X.powerset := by
  ext S
  constructor
  · intro hS
    exact Finset.mem_powerset.mpr (hUX S hS)
  · intro hS
    exact hIncr ∅ hEmpty S (Finset.mem_powerset.mp hS) (Finset.empty_subset S)

/-- Minimal members of `U`: members with no proper subset also in `U`. -/
def minimalMembersIn (_X : Finset α) (U : Finset (Finset α)) : Finset (Finset α) :=
  U.filter fun S => ∀ T ∈ U, ¬ T ⊂ S

@[simp]
lemma mem_minimalMembersIn {X : Finset α} {U : Finset (Finset α)} {S : Finset α} :
    S ∈ minimalMembersIn X U ↔ S ∈ U ∧ ∀ T ∈ U, ¬ T ⊂ S := by
  simp [minimalMembersIn]

lemma minimalMembersIn_subset {X : Finset α} {U : Finset (Finset α)} :
    minimalMembersIn X U ⊆ U := by
  intro S hS
  exact (mem_minimalMembersIn.mp hS).1

/-- Distinct minimal members cannot be related by strict inclusion. -/
lemma not_ssubset_of_mem_minimalMembersIn
    {X : Finset α} {U : Finset (Finset α)} {S T : Finset α}
    (hS : S ∈ minimalMembersIn X U) (hT : T ∈ minimalMembersIn X U) :
    ¬ S ⊂ T := by
  exact (mem_minimalMembersIn.mp hT).2 S ((mem_minimalMembersIn.mp hS).1)

/-- Minimal members form an antichain under inclusion. -/
lemma eq_of_subset_of_mem_minimalMembersIn
    {X : Finset α} {U : Finset (Finset α)} {S T : Finset α}
    (hS : S ∈ minimalMembersIn X U) (hT : T ∈ minimalMembersIn X U)
    (hST : S ⊆ T) :
    S = T := by
  by_contra hne
  exact not_ssubset_of_mem_minimalMembersIn hS hT (hST.ssubset_of_ne hne)

/-- Inclusion antichain predicate for a finite family of finite sets. -/
def InclusionAntichain (A : Finset (Finset α)) : Prop :=
  ∀ S ∈ A, ∀ T ∈ A, S ⊆ T → T ⊆ S

omit [DecidableEq α] in
lemma InclusionAntichain.eq_of_subset {A : Finset (Finset α)}
    (hA : InclusionAntichain A) {S T : Finset α}
    (hS : S ∈ A) (hT : T ∈ A) (hST : S ⊆ T) :
    S = T :=
  le_antisymm hST (hA S hS T hT hST)

/-- Minimal members form an inclusion antichain. -/
lemma minimalMembersIn_inclusionAntichain (X : Finset α) (U : Finset (Finset α)) :
    InclusionAntichain (minimalMembersIn X U) := by
  intro S hS T hT hST
  have hEq : S = T := eq_of_subset_of_mem_minimalMembersIn hS hT hST
  simp [hEq]

/-- Taking minimal members is idempotent. -/
lemma minimalMembersIn_idempotent (X : Finset α) (U : Finset (Finset α)) :
    minimalMembersIn X (minimalMembersIn X U) = minimalMembersIn X U := by
  ext S
  constructor
  · intro hS
    exact minimalMembersIn_subset hS
  · intro hS
    refine mem_minimalMembersIn.mpr ⟨hS, ?_⟩
    intro T hT hTS
    exact not_ssubset_of_mem_minimalMembersIn hT hS hTS

/-- The complexity parameter `ell(U)`: max card of a minimal member,
clamped at 2 so that `Real.log (ell U) ≥ Real.log 2 > 0`. -/
noncomputable def ell (X : Finset α) (U : Finset (Finset α)) : ℕ :=
  max 2 ((minimalMembersIn X U).sup Finset.card)

lemma two_le_ell (X : Finset α) (U : Finset (Finset α)) : 2 ≤ ell X U :=
  le_max_left _ _

lemma ell_pos (X : Finset α) (U : Finset (Finset α)) : 0 < ell X U :=
  lt_of_lt_of_le (by norm_num) (two_le_ell X U)

lemma card_le_ell_of_mem_minimalMembersIn
    {X : Finset α} {U : Finset (Finset α)} {S : Finset α}
    (hS : S ∈ minimalMembersIn X U) :
    S.card ≤ ell X U := by
  unfold ell
  exact (Finset.le_sup (s := minimalMembersIn X U) (f := Finset.card) hS).trans
    (le_max_right _ _)

/-- The complexity parameter is unchanged by replacing a family with its minimal
members. -/
lemma ell_minimalMembersIn_eq (X : Finset α) (U : Finset (Finset α)) :
    ell X (minimalMembersIn X U) = ell X U := by
  unfold ell
  rw [minimalMembersIn_idempotent]

omit [DecidableEq α] in
/-- A one-element member of a family gives a singleton member. -/
lemma exists_singleton_mem_of_mem_card_eq_one
    {U : Finset (Finset α)} {S : Finset α}
    (hS : S ∈ U) (hcard : S.card = 1) :
    ∃ a : α, ({a} : Finset α) ∈ U := by
  rcases Finset.card_eq_one.mp hcard with ⟨a, rfl⟩
  exact ⟨a, hS⟩

/-- A one-element minimal member of a family gives a singleton member of the
family. -/
lemma exists_singleton_mem_of_mem_minimalMembersIn_card_eq_one
    {X : Finset α} {U : Finset (Finset α)} {S : Finset α}
    (hS : S ∈ minimalMembersIn X U) (hcard : S.card = 1) :
    ∃ a : α, ({a} : Finset α) ∈ U :=
  exists_singleton_mem_of_mem_card_eq_one (minimalMembersIn_subset hS) hcard

/-- Every member of `U` contains a minimal member of `U` (as a subset). -/
lemma exists_minimal_subset
    {X : Finset α} {U : Finset (Finset α)}
    {S : Finset α} (hS : S ∈ U) :
    ∃ T ∈ minimalMembersIn X U, T ⊆ S := by
  classical
  -- Pick T₀ ⊆ S in U with minimum card.
  let candidates : Finset (Finset α) := U.filter fun T => T ⊆ S
  have hSc : S ∈ candidates := by
    simp [candidates, hS, subset_refl]
  rcases candidates.exists_min_image Finset.card ⟨S, hSc⟩ with ⟨T₀, hT₀, hmin⟩
  have hT₀U : T₀ ∈ U := (Finset.mem_filter.mp hT₀).1
  have hT₀S : T₀ ⊆ S := (Finset.mem_filter.mp hT₀).2
  refine ⟨T₀, mem_minimalMembersIn.mpr ⟨hT₀U, ?_⟩, hT₀S⟩
  intro T hTU hT_lt
  -- T ⊂ T₀ ⊆ S, so T ⊆ S, so T ∈ candidates, hence T₀.card ≤ T.card,
  -- contradicting T.card < T₀.card.
  have hTS : T ⊆ S := hT_lt.subset.trans hT₀S
  have hTcand : T ∈ candidates := by
    simp [candidates, hTU, hTS]
  have : T₀.card ≤ T.card := hmin T hTcand
  have hlt : T.card < T₀.card := Finset.card_lt_card hT_lt
  exact absurd this (not_le.mpr hlt)

/-- If `U` is nonempty, then its canonical minimal-member cover is nonempty. -/
lemma minimalMembersIn_nonempty_of_nonempty
    {X : Finset α} {U : Finset (Finset α)} (hU : U.Nonempty) :
    (minimalMembersIn X U).Nonempty := by
  rcases hU with ⟨S, hS⟩
  rcases exists_minimal_subset (X := X) hS with ⟨T, hT, _⟩
  exact ⟨T, hT⟩

/-- If `∅` is not a member of `U`, then every minimal member of `U` is
nonempty. -/
lemma nonempty_of_mem_minimalMembersIn_of_empty_not_mem
    {X : Finset α} {U : Finset (Finset α)} {S : Finset α}
    (hEmpty : (∅ : Finset α) ∉ U) (hS : S ∈ minimalMembersIn X U) :
    S.Nonempty := by
  have hSU : S ∈ U := minimalMembersIn_subset hS
  by_contra hS_empty
  have hS_eq : S = ∅ := Finset.not_nonempty_iff_eq_empty.mp hS_empty
  exact hEmpty (by simpa [hS_eq] using hSU)

/-- If `U` has neither `∅` nor singleton members, then every minimal member has
cardinality at least two. -/
lemma two_le_card_of_mem_minimalMembersIn_of_empty_not_mem_of_no_singleton
    {X : Finset α} {U : Finset (Finset α)} {S : Finset α}
    (hEmpty : (∅ : Finset α) ∉ U)
    (hNoSingleton : ∀ a : α, ({a} : Finset α) ∉ U)
    (hS : S ∈ minimalMembersIn X U) :
    2 ≤ S.card := by
  have hnonempty : S.Nonempty :=
    nonempty_of_mem_minimalMembersIn_of_empty_not_mem hEmpty hS
  have hcard_pos : 1 ≤ S.card := Finset.one_le_card.mpr hnonempty
  by_cases hcard_one : S.card = 1
  · rcases exists_singleton_mem_of_mem_minimalMembersIn_card_eq_one hS hcard_one with ⟨a, ha⟩
    exact False.elim ((hNoSingleton a) ha)
  · omega

/-- An increasing family is generated by its minimal members. -/
lemma upClosureIn_minimalMembersIn_eq_of_increasing
    {X : Finset α} {U : Finset (Finset α)}
    (hUX : ∀ S ∈ U, S ⊆ X) (hIncr : IncreasingIn X U) :
    upClosureIn X (minimalMembersIn X U) = U := by
  ext S
  constructor
  · intro hS
    rcases mem_upClosureIn.mp hS with ⟨hSX, T, hTmin, hTS⟩
    exact hIncr T (minimalMembersIn_subset hTmin) S hSX hTS
  · intro hSU
    rcases exists_minimal_subset (X := X) hSU with ⟨T, hTmin, hTS⟩
    exact mem_upClosureIn.mpr ⟨hUX S hSU, T, hTmin, hTS⟩

/-- For an inclusion-antichain generator, the minimal members of its upper
closure are exactly the generators. -/
lemma mem_minimalMembersIn_upClosureIn_iff_of_inclusionAntichain
    {X : Finset α} {A : Finset (Finset α)}
    (hAnti : InclusionAntichain A)
    (hAX : ∀ S ∈ A, S ⊆ X)
    {S : Finset α} :
    S ∈ minimalMembersIn X (upClosureIn X A) ↔ S ∈ A := by
  constructor
  · intro hS
    rcases mem_minimalMembersIn.mp hS with ⟨hSup, hmin⟩
    rcases mem_upClosureIn.mp hSup with ⟨_, S₀, hS₀A, hS₀S⟩
    have hS₀_up : S₀ ∈ upClosureIn X A :=
      mem_upClosureIn.mpr ⟨hAX S₀ hS₀A, S₀, hS₀A, subset_refl _⟩
    have hS₀_not_lt : ¬ S₀ ⊂ S := hmin S₀ hS₀_up
    have hS₀_eq_S : S₀ = S := by
      by_contra hne
      exact hS₀_not_lt (hS₀S.ssubset_of_ne hne)
    simpa [← hS₀_eq_S] using hS₀A
  · intro hSA
    refine mem_minimalMembersIn.mpr ⟨?_, ?_⟩
    · exact mem_upClosureIn.mpr ⟨hAX S hSA, S, hSA, subset_refl _⟩
    · intro T hTup hTlt
      rcases mem_upClosureIn.mp hTup with ⟨_, S₀, hS₀A, hS₀T⟩
      have hS₀S : S₀ ⊆ S := hS₀T.trans hTlt.subset
      have hSS₀ : S ⊆ S₀ := hAnti S₀ hS₀A S hSA hS₀S
      have hST : S ⊆ T := hSS₀.trans hS₀T
      have hTS : T ⊆ S := hTlt.subset
      have hEq : T = S := le_antisymm hTS hST
      exact hTlt.ne hEq

/-- For an inclusion-antichain generator, the minimal-member set of its upper
closure is the generator itself. -/
lemma minimalMembersIn_upClosureIn_eq_of_inclusionAntichain
    {X : Finset α} {A : Finset (Finset α)}
    (hAnti : InclusionAntichain A)
    (hAX : ∀ S ∈ A, S ⊆ X) :
    minimalMembersIn X (upClosureIn X A) = A := by
  ext S
  exact mem_minimalMembersIn_upClosureIn_iff_of_inclusionAntichain hAnti hAX

/-- For an inclusion-antichain generator, `ell` of its upper closure is the
clamped maximum generator size. -/
theorem ell_upClosure_eq_of_inclusionAntichain
    {X : Finset α} {A : Finset (Finset α)}
    (hAnti : InclusionAntichain A)
    (hAX : ∀ S ∈ A, S ⊆ X) :
    ell X (upClosureIn X A) = max 2 (A.sup Finset.card) := by
  unfold ell
  rw [minimalMembersIn_upClosureIn_eq_of_inclusionAntichain hAnti hAX]

/-- Minimal members of the upper closure of a `k`-uniform family have card
at most `k`. -/
lemma minimalMembersIn_upClosureIn_card_le
    {X : Finset α} {A : Finset (Finset α)} {k : ℕ}
    (hUniform : Erdos202.UniformFamily A k)
    (hAX : ∀ S ∈ A, S ⊆ X)
    {S : Finset α} (hS : S ∈ minimalMembersIn X (upClosureIn X A)) :
    S.card ≤ k := by
  classical
  rcases mem_minimalMembersIn.mp hS with ⟨hSup, hmin⟩
  rcases mem_upClosureIn.mp hSup with ⟨hSX, S₀, hS₀A, hS₀S⟩
  -- S₀ is in the closure (it contains itself), so by minimality of S, S₀ ⊄ S.
  have hS₀_up : S₀ ∈ upClosureIn X A :=
    mem_upClosureIn.mpr ⟨(hAX S₀ hS₀A), S₀, hS₀A, subset_refl _⟩
  have hS₀_not_lt : ¬ S₀ ⊂ S := hmin S₀ hS₀_up
  -- Then S₀ = S (since S₀ ⊆ S and S₀ is not a strict subset).
  have hS₀_eq_S : S₀ = S := by
    by_contra hne
    exact hS₀_not_lt (hS₀S.ssubset_of_ne hne)
  -- Hence S.card = S₀.card = k.
  have : S.card = k := hS₀_eq_S ▸ hUniform S₀ hS₀A
  exact this.le

/-- For a uniform family, the minimal members of its upper closure are exactly
the original family. -/
lemma mem_minimalMembersIn_upClosureIn_iff
    {X : Finset α} {A : Finset (Finset α)} {k : ℕ}
    (hUniform : Erdos202.UniformFamily A k)
    (hAX : ∀ S ∈ A, S ⊆ X)
    {S : Finset α} :
    S ∈ minimalMembersIn X (upClosureIn X A) ↔ S ∈ A := by
  constructor
  · intro hS
    rcases mem_minimalMembersIn.mp hS with ⟨hSup, hmin⟩
    rcases mem_upClosureIn.mp hSup with ⟨_, S₀, hS₀A, hS₀S⟩
    have hS₀_up : S₀ ∈ upClosureIn X A :=
      mem_upClosureIn.mpr ⟨hAX S₀ hS₀A, S₀, hS₀A, subset_refl _⟩
    have hS₀_not_lt : ¬ S₀ ⊂ S := hmin S₀ hS₀_up
    have hS₀_eq_S : S₀ = S := by
      by_contra hne
      exact hS₀_not_lt (hS₀S.ssubset_of_ne hne)
    simpa [← hS₀_eq_S] using hS₀A
  · intro hSA
    refine mem_minimalMembersIn.mpr ⟨?_, ?_⟩
    · exact mem_upClosureIn.mpr ⟨hAX S hSA, S, hSA, subset_refl _⟩
    · intro T hTup hTlt
      rcases mem_upClosureIn.mp hTup with ⟨_, S₀, hS₀A, hS₀T⟩
      have hS₀S : S₀ ⊆ S := hS₀T.trans hTlt.subset
      have hS₀_eq_S : S₀ = S := by
        refine Finset.eq_of_subset_of_card_le hS₀S ?_
        rw [hUniform S₀ hS₀A, hUniform S hSA]
      have hST : S ⊆ T := by simpa [hS₀_eq_S] using hS₀T
      have hTS : T ⊆ S := hTlt.subset
      have hTS_eq : T = S := le_antisymm hTS hST
      exact hTlt.ne hTS_eq

/-- For a uniform family, the minimal members of its upper closure are exactly
the original family. -/
lemma minimalMembersIn_upClosureIn_eq
    {X : Finset α} {A : Finset (Finset α)} {k : ℕ}
    (hUniform : Erdos202.UniformFamily A k)
    (hAX : ∀ S ∈ A, S ⊆ X) :
    minimalMembersIn X (upClosureIn X A) = A := by
  ext S
  exact mem_minimalMembersIn_upClosureIn_iff hUniform hAX

/-- **`ell` bound.** The complexity parameter of the upper closure of a
`k`-uniform family is at most `max 2 k`. -/
theorem ell_upClosure_le {X : Finset α} {A : Finset (Finset α)} {k : ℕ}
    (hUniform : Erdos202.UniformFamily A k)
    (hAX : ∀ S ∈ A, S ⊆ X) :
    ell X (upClosureIn X A) ≤ max 2 k := by
  classical
  have hsup_le : (minimalMembersIn X (upClosureIn X A)).sup Finset.card ≤ k := by
    refine Finset.sup_le ?_
    intro S hS
    exact minimalMembersIn_upClosureIn_card_le hUniform hAX hS
  unfold ell
  exact max_le_max le_rfl hsup_le

/-- If the uniform family is nonempty, the complexity of its upper closure is
exactly `max 2 k`. -/
theorem ell_upClosure_eq {X : Finset α} {A : Finset (Finset α)} {k : ℕ}
    (hA : A.Nonempty)
    (hUniform : Erdos202.UniformFamily A k)
    (hAX : ∀ S ∈ A, S ⊆ X) :
    ell X (upClosureIn X A) = max 2 k := by
  have hsup_le : A.sup Finset.card ≤ k := by
    refine Finset.sup_le ?_
    intro S hS
    exact (hUniform S hS).le
  have hk_le_sup : k ≤ A.sup Finset.card := by
    rcases hA with ⟨S, hS⟩
    have hk_le_card : k ≤ S.card := (hUniform S hS).ge
    exact hk_le_card.trans (Finset.le_sup (s := A) (f := Finset.card) hS)
  have hsup_eq : A.sup Finset.card = k := le_antisymm hsup_le hk_le_sup
  unfold ell
  rw [minimalMembersIn_upClosureIn_eq hUniform hAX, hsup_eq]

end

end ParkPham
end Erdos202
